// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      authorization: json['authorization'] as String?,
      driverId: json['driverId'] as String?,
      vehicId: json['vehicId'] as String?,
      driverName: json['driverName'] as String?,
      carNum: json['carNum'] as String?,
      mobile: json['mobile'] as String?,
      telnum: json['telnum'] as String?,
      pushYn: json['pushYn'] as String?,
      talkYn: json['talkYn'] as String?,
      bankCode: json['bankCode'] as String?,
      bankCnnm: json['bankCnnm'] as String?,
      bankAccount: json['bankAccount'] as String?,
      carTypeCode: json['carTypeCode'] as String?,
      carTypeName: json['carTypeName'] as String?,
      carTonCode: json['carTonCode'] as String?,
      carTonName: json['carTonName'] as String?,
      bizName: json['bizName'] as String?,
      bizNum: json['bizNum'] as String?,
      ceo: json['ceo'] as String?,
      bizPost: json['bizPost'] as String?,
      bizAddr: json['bizAddr'] as String?,
      bizAddrDetail: json['bizAddrDetail'] as String?,
      subBizNum: json['subBizNum'] as String?,
      bizKind: json['bizKind'] as String?,
      bizCond: json['bizCond'] as String?,
      socNo: json['socNo'] as String?,
      driverEmail: json['driverEmail'] as String?,
      vehicCnt: json['vehicCnt'] as int?,
      dangerGoodsYn: json['dangerGoodsYn'] as String?,
      chemicalsYn: json['chemicalsYn'] as String?,
      foreignLicenseYn: json['foreignLicenseYn'] as String?,
      forkliftYn: json['forkliftYn'] as String?,
      cargoBox: json['cargoBox'] as String?,
      bankchkDate: json['bankchkDate'] as String?,
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'authorization': instance.authorization,
      'driverId': instance.driverId,
      'vehicId': instance.vehicId,
      'driverName': instance.driverName,
      'carNum': instance.carNum,
      'mobile': instance.mobile,
      'telnum': instance.telnum,
      'pushYn': instance.pushYn,
      'talkYn': instance.talkYn,
      'bankCode': instance.bankCode,
      'bankCnnm': instance.bankCnnm,
      'bankAccount': instance.bankAccount,
      'carTypeCode': instance.carTypeCode,
      'carTypeName': instance.carTypeName,
      'carTonCode': instance.carTonCode,
      'carTonName': instance.carTonName,
      'bizName': instance.bizName,
      'bizNum': instance.bizNum,
      'ceo': instance.ceo,
      'bizPost': instance.bizPost,
      'bizAddr': instance.bizAddr,
      'bizAddrDetail': instance.bizAddrDetail,
      'subBizNum': instance.subBizNum,
      'bizKind': instance.bizKind,
      'bizCond': instance.bizCond,
      'socNo': instance.socNo,
      'driverEmail': instance.driverEmail,
      'vehicCnt': instance.vehicCnt,
      'dangerGoodsYn': instance.dangerGoodsYn,
      'chemicalsYn': instance.chemicalsYn,
      'foreignLicenseYn': instance.foreignLicenseYn,
      'forkliftYn': instance.forkliftYn,
      'cargoBox': instance.cargoBox,
      'bankchkDate': instance.bankchkDate,
    };
