// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKO4C62N6VW896fYjK4Nu5Hb3DiiQvqYo',
    appId: '1:843222466718:web:83f40924f20dfb6ae9bb8f',
    messagingSenderId: '843222466718',
    projectId: 'logislinkflutter-9f180',
    authDomain: 'logislinkflutter-9f180.firebaseapp.com',
    storageBucket: 'logislinkflutter-9f180.appspot.com',
    measurementId: 'G-PK1WBPE3XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-LcVr3DycYl4V6Gm1q_FCxgRLKbW_LK0',
    appId: '1:843222466718:android:ba80ec3e86aa1656e9bb8f',
    messagingSenderId: '843222466718',
    projectId: 'logislinkflutter-9f180',
    storageBucket: 'logislinkflutter-9f180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJLsG1os71SDt_mWBogWEIoaRN5bDgkew',
    appId: '1:843222466718:ios:bbc18414c643f41de9bb8f',
    messagingSenderId: '843222466718',
    projectId: 'logislinkflutter-9f180',
    storageBucket: 'logislinkflutter-9f180.appspot.com',
    iosClientId: '843222466718-dlpr07u3lhflljb7ooktaul11sp2pnnb.apps.googleusercontent.com',
    iosBundleId: 'com.logislink.driver.logislinkDriverFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJLsG1os71SDt_mWBogWEIoaRN5bDgkew',
    appId: '1:843222466718:ios:9afcfa262430dfd9e9bb8f',
    messagingSenderId: '843222466718',
    projectId: 'logislinkflutter-9f180',
    storageBucket: 'logislinkflutter-9f180.appspot.com',
    iosClientId: '843222466718-gu5mhjs2dhc84odl0vl4b99dbj1q88on.apps.googleusercontent.com',
    iosBundleId: 'com.logislink.driver.logislinkDriverFlutter.RunnerTests',
  );
}
