// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6b9affz9gcOlCbtNCFMFS4kBKcXPWuCI',
    appId: '1:443385345478:web:c6315af273c7406b6ceec7',
    messagingSenderId: '443385345478',
    projectId: 'logislink-driver',
    authDomain: 'logislink-driver.firebaseapp.com',
    storageBucket: 'logislink-driver.appspot.com',
    measurementId: 'G-PC2B6SX1JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaKwzzlH3iA9y1Tw792TqjJP24J67G1Zg',
    appId: '1:443385345478:android:631fbcf78abcae9d6ceec7',
    messagingSenderId: '443385345478',
    projectId: 'logislink-driver',
    storageBucket: 'logislink-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcYQfFQOplcKTRM86K_nBg4_MFv0o2YqA',
    appId: '1:443385345478:ios:235bef95aabf8a6e6ceec7',
    messagingSenderId: '443385345478',
    projectId: 'logislink-driver',
    storageBucket: 'logislink-driver.appspot.com',
    iosBundleId: 'com.logislink.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcYQfFQOplcKTRM86K_nBg4_MFv0o2YqA',
    appId: '1:443385345478:ios:867fcb938da5e67e6ceec7',
    messagingSenderId: '443385345478',
    projectId: 'logislink-driver',
    storageBucket: 'logislink-driver.appspot.com',
    iosBundleId: 'com.logislink.driver.logislinkDriverFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6b9affz9gcOlCbtNCFMFS4kBKcXPWuCI',
    appId: '1:443385345478:web:419d090bfed7d81e6ceec7',
    messagingSenderId: '443385345478',
    projectId: 'logislink-driver',
    authDomain: 'logislink-driver.firebaseapp.com',
    storageBucket: 'logislink-driver.appspot.com',
    measurementId: 'G-3YW92WC59Z',
  );

}